name: Pull Request Checks
run-name: ${{ github.actor}} - ${{ github.event_name }} - ${{ github.sha }}
on: [push]
jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: echo "Tests are not yet implemented."
      - name: Run linter
        run: bun run lint:check
  success:
    runs-on: ubuntu-latest
    needs: pr-checks
    if: success()
    steps:
      - name: Happy dance
        run: echo "🚀 We are flying"
  failure:
    runs-on: ubuntu-latest
    needs: pr-checks
    if: failure()
    steps:
      - name: Sad dance
        run: echo "😢 We are crying"
